site_name: Linked Data Objects (LDO)
site_url: https://ldo.js.org
repo_url: https://github.com/o-development/ldo
copyright: Copyright &copy; 2016 - 2020 Martin Donath
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
nav:
  - Guides:
    - For Raw Rdf:
      - raw_rdf/index.md
      - Setup: raw_rdf/setup.md
    - For Solid:
      - solid/index.md
    - For Solid+React:
      - solid_react/index.md
    - Advanced Data Manipulation:
      - advanced_data_manipulation/index.md
  - API:
    - 'api/index.md'
    - '@ldo/cli':
      - 'api/cli/index.md'
      - init: 'api/cli/init.md'
      - build: 'api/cli/build.md'
    - '@ldo/ldo':
      - 'api/ldo/index.md'
      - Getting an LDO dataset:
        - 'api/ldo/getting_an_ldo_dataset/index.md'
        - createLdoDataset: 'api/ldo/getting_an_ldo_dataset/createldodataset.md'
        - parseRdf: 'api/ldo/getting_an_ldo_dataset/parserdf.md'
        - LDO Dataset Factory:
          - 'api/ldo/getting_an_ldo_dataset/ldodatasetfactory/index.md'
          - createLdoDatasetFactory: 'api/ldo/getting_an_ldo_dataset/ldodatasetfactory/createldodatasetfactory.md'
          - LdoDatasetFactory: 'api/ldo/getting_an_ldo_dataset/ldodatasetfactory/ldodatasetfactory.md'
    - '@ldo/solid': 'api/solid/index.md'
    - '@ldo/solid-react': 'api/solid-react/index.md'
    - '@ldo/jsonld-dataset-proxy': 'api/jsonld-dataset-proxy/index.md'
    - '@ldo/dataset': 'api/dataset/index.md'
    - '@ldo/subscribable-dataset': 'api/subscribable-dataset/index.md'
    - '@ldo/schema-converter-shex': 'api/schema-converter-shex/index.md'
    - '@ldo/traverser-shexj': 'api/traverser-shexj/index.md'
    - '@ldo/type-traverser': 'api/type-traverser/index.md'
    - '@ldo/rdf-utils': 'api/rdf-utils/index.md'
theme:
    name: material
    custom_dir: overrides
    logo: assets/Logo-40.png
    language: en
    favicon: assets/favicon.png
    palette:
      scheme: slate
      primary: black
    features:
      - navigation.instant
      - navigation.tracking
      - navigation.sections
      - navigation.indexes
      - toc.follow
      - search.suggest
      - search.highlight

