site_name: Linked Data Objects (LDO)
site_url: https://ldo.js.org
repo_url: https://github.com/o-development/ldo
copyright: Copyright &copy; 2016 - 2020 Martin Donath
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
nav:
  - Guides:
    - 'guides/index.md'
    - For Raw Rdf: guides/raw_rdf/index.md
    # - For Solid:
    #   - guides/solid/index.md
    - For Solid+React: guides/solid_react/index.md
    - Advanced Data Manipulation:
      - guides/advanced_data_manipulation/index.md
  - API:
    - 'api/index.md'
    - '@ldo/cli':
      - 'api/cli/index.md'
      - init: 'api/cli/init.md'
      - build: 'api/cli/build.md'
    - '@ldo/ldo':
      - 'api/ldo/index.md'
      - LdoBase: 'api/ldo/LdoBase.md'
      - ShapeType: 'api/ldo/ShapeType.md'
      - parseRdf: 'api/ldo/parseRdf.md'
      - createLdoDatasetFactory: 'api/ldo/createLdoDatasetFactory.md'
      - LdoDatasetFactory: 'api/ldo/LdoDatasetFactory.md'
      - createLdoDataset: 'api/ldo/createLdoDataset.md'
      - LdoDataset: 'api/ldo/LdoDataset.md'
      - LdoBuilder: 'api/ldo/LdoBuilder.md'
      - toTurtle: 'api/ldo/toTurtle.md'
      - toNTriples: 'api/ldo/toNTriples.md'
      - serialize: 'api/ldo/serialize.md'
      - transactions: 'api/ldo/transactions.md'
      - toSparqlUpdate: 'api/ldo/toSparqlUpdate.md'
      - languageOf: 'api/ldo/languageOf.md'
      - setLanguagePreferences: 'api/ldo/setLanguagePreferences.md'
      - graphOf: 'api/ldo/graphOf.md'
      - write: 'api/ldo/write.md'
      - getDataset: 'api/ldo/getDataset.md'
    - '@ldo/solid':
      - 'api/solid/README.md'
      - createSolidLdoDataset: 'api/solid/functions/createSolidLdoDataset.md'
      - SolidLdoDataset: 'api/solid/classes/SolidLdoDataset.md'
      - LeafUri: 'api/solid/types/LeafUri.md'
      - ContainerUri: 'api/solid/types/ContainerUri.md'
      - Leaf: 'api/solid/classes/Leaf.md'
      - Container: 'api/solid/classes/Container.md'
      - checkRootContainer: 'api/solid/functions/checkRootContainer.md'
      - createDataResource: 'api/solid/functions/createDataResource.md'
      - deleteResource: 'api/solid/functions/deleteResource.md'
      - readResource: 'api/solid/functions/readResource.md'
      - updateDataResource: 'api/solid/functions/updateDataResource.md'
      - uploadResource: 'api/solid/functions/uploadResource.md'
      - getWacUri: 'api/solid/functions/getWacUri.md'
      - getWacRuleWithAclUri: 'api/solid/functions/getWacRuleWithAclUri.md'
      - setWacRuleForAclUri: 'api/solid/functions/setWacRuleForAclUri.md'
      - changeData: 'api/solid/functions/changeData.md'
      - commitData: 'api/solid/functions/commitData.md'
    - '@ldo/solid-react':
      - 'api/solid-react/index.md'
      - BrowserSolidLdoProvider: 'api/solid-react/BrowserSolidLdoProvider.md'
      - SolidLdoProvider: 'api/solid-react/SolidLdoProvider.md'
      - useLdo: 'api/solid-react/useLdo.md'
      - useResource: 'api/solid-react/useResource.md'
      - useRootContainer: 'api/solid-react/useRootContainer.md'
      - useSolidAuth: 'api/solid-react/useSolidAuth.md'
      - useSubject: 'api/solid-react/useSubject.md'

    # - '@ldo/jsonld-dataset-proxy': 'api/jsonld-dataset-proxy/index.md'
    # - '@ldo/dataset': 'api/dataset/index.md'
    # - '@ldo/subscribable-dataset': 'api/subscribable-dataset/index.md'
    # - '@ldo/schema-converter-shex': 'api/schema-converter-shex/index.md'
    # - '@ldo/traverser-shexj': 'api/traverser-shexj/index.md'
    # - '@ldo/type-traverser': 'api/type-traverser/index.md'
    # - '@ldo/rdf-utils': 'api/rdf-utils/index.md'
theme:
    name: material
    custom_dir: overrides
    logo: assets/Logo-40.png
    language: en
    favicon: assets/favicon.png
    palette:
      scheme: slate
      primary: black
    features:
      - navigation.instant
      - navigation.tracking
      - navigation.sections
      - navigation.indexes
      - navigation.footer
      - toc.follow
      - search.suggest
      - search.highlight

